export const FMEA_ACTION_TYPES = {
    FETCH_FMEA_START:'FETCH_FMEA_START',
    FETCH_FMEA_SUCCESS :'FETCH_FMEA_SUCCESS',
    FETCH_FMEA_FAIL :'FETCH_FMEA_FAIL',
    SET_FMEA_DATA :'SET_FMEA_DATA'
  };
  