export const MODAL_ACTION_TYPES = {
  SET_MODAL_IS_OPEN: "SET_MODAL_IS_OPEN",
  SET_MODAL_DATA: "SET_MODAL_DATA",
  SET_MODAL_ANALYSES_IS_OPEN: "SET_MODAL_ANALYSES_IS_OPEN",
  SET_ANALYSES: "SET_ANALYSES",
  SET_MODAL_SOD_IS_OPEN: "SET_MODAL_SOD_IS_OPEN",
  SET_SOD_TYPE: "SET_SOD_TYPE",
  SET_SOD_OBJECT: "SET_SOD_OBJECT",
};
